import { readFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import 'nbook/test/source-contract-matcher'
import type { SubjectStateDto } from 'nbook/app/components/novel-ide/world-engine/world-engine-workbench.types'
import type {
  WorldWorkbenchPreviewSlice,
  WorldWorkbenchPreviewSnapshot,
} from 'nbook/app/components/novel-ide/world-engine/workbench-preview/world-engine-workbench-preview.types'
import {
  cloneMockWorkbenchSlices,
  mockWorkbenchSchema,
  mockWorkbenchSubjects,
} from 'nbook/app/utils/world-engine-workbench-preview-mock'
import {
  applyWorkbenchPreviewMutationListPatch,
  applyWorkbenchPreviewMutationPatch,
  reduceWorkbenchPreviewSnapshots,
} from 'nbook/app/utils/world-engine-workbench-preview-state'
import {
  formatWorkbenchPreviewValue,
  parseWorkbenchPreviewMutationValue,
} from 'nbook/app/utils/world-engine-workbench-preview-value'
import {
  buildWorkbenchPreviewFiltersAfterSavedEdit,
  matchesWorkbenchPreviewSliceFilter,
} from 'nbook/app/utils/world-engine-workbench-preview-filter'
import { isWorldWorkbenchSubjectSystemMaintenanceSlice } from 'nbook/app/utils/world-engine-workbench-slice-classifier'

const pagePath = fileURLToPath(new URL('../pages/world-engine.workbench-preview.vue', import.meta.url))
const workbenchDialogPath = fileURLToPath(new URL('../components/novel-ide/world-engine/WorldEngineWorkbenchDialog.vue', import.meta.url))
const mockPath = fileURLToPath(new URL('./world-engine-workbench-preview-mock.ts', import.meta.url))
const stateUtilPath = fileURLToPath(new URL('./world-engine-workbench-preview-state.ts', import.meta.url))
const valueUtilPath = fileURLToPath(new URL('./world-engine-workbench-preview-value.ts', import.meta.url))
const filterUtilPath = fileURLToPath(new URL('./world-engine-workbench-preview-filter.ts', import.meta.url))
const realUtilPath = fileURLToPath(new URL('./world-engine-workbench-real.ts', import.meta.url))
const sidebarPath = fileURLToPath(new URL('../components/novel-ide/world-engine/workbench-preview/WorldEngineWorkbenchPreviewSidebar.vue', import.meta.url))
const sliceListPath = fileURLToPath(new URL('../components/novel-ide/world-engine/workbench-preview/WorldEngineWorkbenchPreviewSliceList.vue', import.meta.url))
const sliceCardPath = fileURLToPath(new URL('../components/novel-ide/world-engine/workbench-preview/WorldEngineWorkbenchPreviewSliceCard.vue', import.meta.url))
const inspectorPath = fileURLToPath(new URL('../components/novel-ide/world-engine/workbench-preview/WorldEngineWorkbenchPreviewInspector.vue', import.meta.url))
const editorPath = fileURLToPath(new URL('../components/novel-ide/world-engine/workbench-preview/WorldEngineWorkbenchPreviewMutationEditor.vue', import.meta.url))
const patchEditorPath = fileURLToPath(new URL('../components/novel-ide/world-engine/workbench-preview/WorldEngineWorkbenchPreviewPatchEditor.vue', import.meta.url))
const sliceComposerPath = fileURLToPath(new URL('../components/novel-ide/world-engine/WorldEngineMutationEditor.vue', import.meta.url))
const valueInputPath = fileURLToPath(new URL('../components/novel-ide/world-engine/workbench-preview/WorldEngineWorkbenchPreviewValueInput.vue', import.meta.url))
const typesPath = fileURLToPath(new URL('../components/novel-ide/world-engine/workbench-preview/world-engine-workbench-preview.types.ts', import.meta.url))
const comboboxPath = fileURLToPath(new URL('../components/common/form/Combobox.vue', import.meta.url))
const formNumberInputPath = fileURLToPath(new URL('../components/common/form/FormNumberInput.vue', import.meta.url))
const formSelectPath = fileURLToPath(new URL('../components/common/form/FormSelect.vue', import.meta.url))
const segmentedControlPath = fileURLToPath(new URL('../components/common/form/SegmentedControl.vue', import.meta.url))
const lowCodeRadioPath = fileURLToPath(new URL('../components/common/low-code-form/LowCodeRadioField.vue', import.meta.url))
const zhLocalePath = fileURLToPath(new URL('../i18n/locales/zh-CN.ts', import.meta.url))
const enLocalePath = fileURLToPath(new URL('../i18n/locales/en-US.ts', import.meta.url))

function removedToken(...parts: string[]): string {
  return parts.join('')
}

async function readSource(path: string): Promise<string> {
  return (await readFile(path, 'utf-8')).replace(/\r\n/g, '\n')
}

function findSnapshotSubject(snapshots: WorldWorkbenchPreviewSnapshot[], sliceId: string, subjectId: string): SubjectStateDto {
  const snapshot = snapshots.find(item => item.sliceId === sliceId)
  const subject = snapshot?.subjects.find(item => item.subjectId === subjectId)
  expect(subject).toBeTruthy()
  return subject as SubjectStateDto
}

describe('World Engine Workbench preview redesign', () => {
  it('保留 mock 数据源和三栏 preview 入口', async () => {
    const page = await readSource(pagePath)
    const workbenchDialog = await readSource(workbenchDialogPath)
    const mock = await readSource(mockPath)
    const stateUtil = await readSource(stateUtilPath)
    const valueUtil = await readSource(valueUtilPath)
    const filterUtil = await readSource(filterUtilPath)
    const realUtil = await readSource(realUtilPath)
    const sidebar = await readSource(sidebarPath)
    const sliceList = await readSource(sliceListPath)
    const sliceCard = await readSource(sliceCardPath)
    const inspector = await readSource(inspectorPath)
    const editor = await readSource(editorPath)
    const patchEditor = await readSource(patchEditorPath)
    const sliceComposer = await readSource(sliceComposerPath)
    const valueInput = await readSource(valueInputPath)
    const types = await readSource(typesPath)
    const combobox = await readSource(comboboxPath)
    const formNumberInput = await readSource(formNumberInputPath)
    const formSelect = await readSource(formSelectPath)
    const segmentedControl = await readSource(segmentedControlPath)
    const lowCodeRadio = await readSource(lowCodeRadioPath)
    const zhLocale = await readSource(zhLocalePath)
    const enLocale = await readSource(enLocalePath)

    expect(page).toContainSource('World Engine Workbench Preview')
    expect(page).toContainSource('WorldEngineWorkbenchPreviewSidebar')
    expect(page).toContainSource('WorldEngineWorkbenchPreviewSliceList')
    expect(page).toContainSource('WorldEngineWorkbenchPreviewMutationEditor')
    expect(page).toContainSource('WorldEngineWorkbenchPreviewInspector')
    expect(page).toContainSource('world-engine-workbench-preview world-engine-workbench-theme')
    expect(page).not.toContainSource('--we-bg-canvas: #f6f8f7')
    expect(page).not.toContainSource('--we-bg-panel: #ffffff')
    expect(page).not.toContainSource('--we-accent: #078768')
    expect(page).not.toContainSource('--bg-main: var(--we-bg-canvas)')
    expect(page).not.toContainSource('--accent-main: var(--we-accent)')
    expect(page).toContainSource('mock 数据源')
    expect(page).toContainSource('mockWorkbenchSubjectSystemSummaries')
    expect(page).toContainSource(':subject-system-summaries="mockWorkbenchSubjectSystemSummaries"')
    expect(page).toContainSource('function openMockWorkspacePath(path: string): void')
    expect(page).toContainSource('mock 预览不会打开真实文件')
    expect(page).toContainSource('function commitMockSubjectEventProposal(proposal: WorldWorkbenchSubjectFileProposal): void')
    expect(page).toContainSource('mock 预览不会写入 events.jsonl')
    expect(page).toContainSource('@commit-subject-event-proposal="commitMockSubjectEventProposal"')
    expect(page).toContainSource('@open-workspace-path="openMockWorkspacePath"')
    expect(page.match(/@open-workspace-path="openMockWorkspacePath"/g)?.length).toBeGreaterThanOrEqual(2)
    expect(page).toContainSource('inspectorVisible')
    expect(page).toContainSource('v-show="inspectorVisible"')
    expect(page).toContainSource('applySlicePatch')
    expect(page).toContainSource('applyMutationValuePatch')
    expect(page).toContainSource('applyWorkbenchPreviewMutationPatch')
    expect(page).toContainSource('reduceWorkbenchPreviewSnapshots')
    expect(page).toContainSource('resetMockData')
    expect(page).toContainSource('resetVersion')
    expect(page).toContainSource('subjectFilterMode')
    expect(page).toContainSource('isSubjectFilterMode')
    expect(page).toContainSource('sliceSearch')
    expect(page).toContainSource('sliceKindFilter')
    expect(page).toContainSource('sliceHealthFilter')
    expect(page).toContainSource('isSliceHealthFilter')
    expect(page).toContainSource('filter === \'draft\'')
    expect(page).toContainSource('focusedSubjectId')
    expect(page).toContainSource('focusSubject')
    expect(page).toContainSource('function focusSubjectContext(subjectId: string): void')
    expect(page).toContainSource('function clearSubjectContext(): void')
    expect(page).toContainSource(':focused-subject-id="focusedSubjectId"')
    expect(page).toContainSource('@focus-subject-context="focusSubjectContext"')
    expect(page).toContainSource('@clear-subject-context="clearSubjectContext"')
    expect(sidebar).toContainSource('const activeSubjectContextId = computed(() => props.focusedSubjectId && subjectSystemSummaryMap.value.has(props.focusedSubjectId) ? props.focusedSubjectId : \'\')')
    expect(sidebar).toContainSource('v-if="activeSubjectContextId"')
    expect(sidebar).toContainSource(':aria-pressed="activeSubjectContextId === subject.id"')
    expect(sidebar).toContainSource('{{ activeSubjectContextId === subject.id ? "语境中" : "语境" }}')
    expect(page).toContainSource('focusReviewIssue')
    expect(page).toContainSource('highlightedMutationFocus')
    expect(page).toContainSource('clearMutationFocus')
    expect(page).toContainSource('removeSubjectFilter')
    expect(page).toContainSource('previousSnapshotSubjects')
    expect(page).toContainSource('localDraftStorageKey')
    expect(page).toContainSource('restoreLocalDraft')
    expect(page).toContainSource('persistLocalDraft')
    expect(page).toContainSource('isLocalDraft')
    expect(page).toContainSource('localDraftSuppressed')
    expect(page).toContainSource('subjectStats')
    expect(page).toContainSource('WorldWorkbenchPreviewSubjectStat')
    expect(page).toContainSource('reviewQueueItems')
    expect(page).toContainSource('currentReviewQueueIndex')
    expect(page).toContainSource('WorldWorkbenchPreviewReviewQueueItem')
    expect(page).toContainSource('issueTriageStates')
    expect(page).toContainSource('reviewQueueMode')
    expect(page).toContainSource('isReviewQueueMode')
    expect(page).toContainSource('updateIssueTriage')
    expect(page).toContainSource('reviewTriageSummary')
    expect(page).toContainSource('sliceReviewSummaries')
    expect(page).toContainSource('WorldWorkbenchPreviewSliceReviewSummary')
    expect(page).toContainSource('worldViewFilterParts')
    expect(page).toContainSource('const modeLabel = subjectFilterMode.value === \'all\' ? \'全部 subject\' : \'任一 subject\'')
    expect(page).toContainSource([
      'function clearSubjectFilter(): void {',
      '  selectedSubjectIds.value = []',
      '  subjectFilterMode.value = \'any\'',
      '}',
    ].join('\n'))
    expect(page).toContainSource('subjectFilterMode.value = selectedSubjectIds.value.length && isSubjectFilterMode(draft.subjectFilterMode) ? draft.subjectFilterMode : \'any\'')
    expect(page).toContainSource([
      'function removeSubjectFilter(subjectId: string): void {',
      '  selectedSubjectIds.value = selectedSubjectIds.value.filter(id => id !== subjectId)',
      '  if (!selectedSubjectIds.value.length) {',
      '    subjectFilterMode.value = \'any\'',
      '  }',
      '}',
    ].join('\n'))
    expect(page).toContainSource('当前视角')
    expect(page).toContainSource('sliceHealthFilterLabel')
    expect(page).toContainSource('shortFilterText')
    expect(page).toContainSource('draft.version === 4')
    expect(page).toContainSource('neuro-book:world-engine-workbench-preview:draft:v4')
    expect(page).toContainSource('defaultSidebarWidth')
    expect(page).toContainSource('defaultInspectorWidth')
    expect(page).toContainSource('const defaultSidebarWidth = 320')
    expect(page).toContainSource('const defaultInspectorWidth = 420')
    expect(page).toContainSource('defaultMutationEditorHeight')
    expect(page).toContainSource('sidebarWidth = ref(defaultSidebarWidth)')
    expect(page).toContainSource('inspectorWidth = ref(defaultInspectorWidth)')
    expect(page).toContainSource('mutationEditorHeight = ref(defaultMutationEditorHeight)')
    expect(page).toContainSource('validPanelSize')
    expect(page).toContainSource('draft.sidebarWidth, 220, 420, defaultSidebarWidth')
    expect(page).toContainSource('draft.inspectorWidth, 300, 560, defaultInspectorWidth')
    expect(page).toContainSource('draft.mutationEditorHeight, 160, 520, defaultMutationEditorHeight')
    expect(page).toContainSource('sidebarWidth: sidebarWidth.value')
    expect(page).toContainSource('inspectorWidth: inspectorWidth.value')
    expect(page).toContainSource('mutationEditorHeight: mutationEditorHeight.value')
    expect(page).toContainSource('typeof draft.sidebarWidth === \'number\'')
    expect(page).toContainSource('typeof draft.inspectorWidth === \'number\'')
    expect(page).toContainSource('typeof draft.mutationEditorHeight === \'number\'')
    expect(page).toContainSource(':width="sidebarWidth"')
    expect(page).toContainSource(':width="inspectorWidth"')
    expect(page).toContainSource(':height="mutationEditorHeight"')
    expect(page).toContainSource('@update:width="sidebarWidth = $event"')
    expect(page).toContainSource('@update:width="inspectorWidth = $event"')
    expect(page).toContainSource('@update:height="mutationEditorHeight = $event"')
    expect(page).toContainSource('world-inspector-restore-rail')
    expect(page).toContainSource('toggleInspectorPanel')
    expect(page).toContainSource('@click="toggleInspectorPanel"')
    expect(page).toContainSource('浏览器临时 mock')
    expect(page).toContainSource('已恢复浏览器草稿')
    expect(page).toContainSource('localStorage.removeItem(localDraftStorageKey)')
    expect(page).toContainSource('mutationEditorCollapsed = ref(true)')
    expect(page).toContainSource('metadataDraftSummaries')
    expect(page).toContainSource('WorldWorkbenchPreviewMetadataDraftSummary')
    expect(page).toContainSource('update-metadata-drafts')
    expect(page).toContainSource('metadataDraftSliceCount')
    expect(page).toContainSource('valueDraftSliceCount')
    expect(page).toContainSource('draftSliceIds')
    expect(page).toContainSource('totalDraftSliceCount')
    expect(page).toContainSource('draftSummaryTitle')
    expect(page).toContainSource('inspectorButtonTitle')
    expect(page).toContainSource('world-workbench-inspector-toggle')
    expect(page).toContainSource('world-workbench-draft-summary')
    expect(page).toContainSource('showAllDraftSlices')
    expect(page).toContainSource('worldEngine.workbenchPreview.drafts')
    expect(page).toContainSource('meta {{ metadataDraftSliceCount }}')
    expect(page).toContainSource('value {{ valueDraftSliceCount }}')
    expect(page).toContainSource('metadata 草稿')
    expect(page).toContainSource('valueDraftSummaries')
    expect(page).toContainSource('WorldWorkbenchPreviewValueDraftSummary')
    expect(page).toContainSource('update-value-drafts')
    expect(page).toContainSource('openDraftSurfacesForSlice')
    expect(page).toContainSource('openInspectorPanel')
    expect(page).toContainSource('expandMutationEditorPanel')
    expect(page).toContainSource(':open-inspector-panel="openInspectorPanel"')
    expect(page).toContainSource('const subjectFileProposalFocusVersion = ref(0)')
    expect(page).toContainSource('function openInspectorPanel(target?: \'subject-file-proposals\'): void')
    expect(page).toContainSource('function toggleInspectorPanel(): void')
    expect(page).toContainSource('openInspectorPanel(selectedSliceSubjectFileProposalCount.value ? \'subject-file-proposals\' : undefined)')
    expect(page).toContainSource('selectedSliceSubjectFileProposalCount')
    expect(page).toContainSource('inspectorButtonAttentionClass')
    expect(page).toContainSource('data-testid="world-workbench-inspector-proposal-count"')
    expect(page).toContainSource('data-testid="world-inspector-restore-proposal-count"')
    expect(page).toContainSource('subjectFileProposalFocusVersion.value += 1')
    expect(page).toContainSource(':subject-file-proposal-focus-version="subjectFileProposalFocusVersion"')
    expect(page).toContainSource('metadataDraftSummaries.value.some(draft => draft.sliceId === firstDraftSliceId)')
    expect(page).toContainSource('valueDraftSummaries.value.some(draft => draft.sliceId === firstDraftSliceId)')
    expect(page).toContainSource(':open-draft-inspector="openInspectorPanel"')
    expect(page).toContainSource(':expand-draft-editor="expandMutationEditorPanel"')
    expect(page).toContainSource('sliceHealthFilter.value !== \'draft\'')
    expect(page).toContainSource('inspectorVisible.value = true')
    expect(page).toContainSource('mutationEditorCollapsed.value = false')

    expect(mock).toContainSource('mockWorkbenchSchema')
    expect(mock).toContainSource('mockWorkbenchSubjects')
    expect(mock).toContainSource('mockWorkbenchSubjectSystemSummaries')
    expect(mock).toContainSource('mockWorkbenchSlices')
    expect(mock).toContainSource('mockWorkbenchSnapshots')
    expect(mock).toContainSource('world')
    expect(mock).toContainSource('location')
    expect(mock).toContainSource('character')
    expect(mock).toContainSource('item')
    expect(mock).toContainSource('backstory')
    expect(mock).toContainSource('remove/append 编辑路径')
    expect(mock).toContainSource('masked')
    expect(mock).toContainSource('旧剑旧伤补充可能遮蔽艾莉娜此前对东塔线索的理解')
    expect(mock).not.toContainSource(removedToken('cor', 'rection'))
    expect(mock).toContainSource('findMockSnapshot')
    expect(stateUtil).toContainSource('applyWorkbenchPreviewMutationPatch')
    expect(stateUtil).toContainSource('reduceWorkbenchPreviewSnapshots')
    expect(stateUtil).toContainSource('schema default')
    expect(stateUtil).toContainSource('replace')
    expect(stateUtil).toContainSource('increment')
    expect(stateUtil).toContainSource('append')
    expect(valueUtil).toContainSource('parseWorkbenchPreviewMutationValue')
    expect(valueUtil).toContainSource('formatWorkbenchPreviewValue')
    expect(filterUtil).toContainSource('matchesWorkbenchPreviewSliceFilter')
    expect(filterUtil).toContainSource('matchesWorkbenchPreviewSubjectFilter')
    expect(filterUtil).toContainSource('matchesWorkbenchPreviewKindFilter')
    expect(filterUtil).toContainSource('matchesWorkbenchPreviewHealthFilter')
    expect(filterUtil).toContainSource('metadataDraftCount')
    expect(filterUtil).toContainSource('valueDraftCount')
    expect(filterUtil).toContainSource('matchesWorkbenchPreviewKeywordFilter')
    expect(filterUtil).toContainSource('buildWorkbenchPreviewFiltersAfterSavedEdit')
    expect(realUtil).toContainSource('sourceLabel: sourceKind === \'direct-mutation\' ? \'直接触及该主体\' : \'当前主体语境下的 world 事件建议\'')
    expect(realUtil).toContainSource('`source: ${proposal.sourceLabel}`')
    expect(realUtil).toContainSource('`sliceId: ${proposal.sliceId}`')
    expect(realUtil).toContainSource('sliceId: input.slice.id')
    expect(formSelect).toContainSource('type SelectSize = \'default\' | \'sm\'')
    expect(formSelect).toContainSource('size?: SelectSize')
    expect(formSelect).toContainSource(':style="panelStyle"')
    expect(formSelect).not.toContainSource('panelSizeClass')
    expect(combobox).toContainSource('type ComboboxSize = \'default\' | \'sm\'')
    expect(combobox).toContainSource('autocomplete="off"')
    expect(combobox).toContainSource('disabled?: boolean')
    expect(formNumberInput).toContainSource('type NumberInputSize = \'default\' | \'sm\'')
    expect(formNumberInput).toContainSource('inputmode="decimal"')
    expect(formNumberInput).toContainSource('stepValueBy')
    expect(formNumberInput).toContainSource('i-lucide-chevron-up')
    expect(segmentedControl).toContainSource('SegmentedControlOption')
    expect(segmentedControl).toContainSource('SegmentedControlValue')
    expect(segmentedControl).toContainSource('count?: number | string')
    expect(segmentedControl).toContainSource('disabled?: boolean')
    expect(segmentedControl).toContainSource('title?: string')
    expect(segmentedControl).toContainSource('tone?: SegmentedControlTone')
    expect(segmentedControl).toContainSource('(e: \'update:modelValue\', value: SegmentedControlValue): void')
    expect(segmentedControl).toContainSource(':aria-pressed="isSelected(option)"')
    expect(segmentedControl).toContainSource(':data-testid="option.testId"')
    expect(segmentedControl).toContainSource('option.disabled')
    expect(lowCodeRadio).toContainSource('SegmentedControl')
    expect(lowCodeRadio).toContainSource('SegmentedControlValue')
    expect(lowCodeRadio).toContainSource('props.field.options.map')

    expect(sidebar).toContainSource('Schema')
    expect(sidebar).toContainSource('const schemaSourcePath = "world-engine/schema/index.ts";')
    expect(sidebar).toContainSource('const calendarSourcePath = "world-engine/calendar.ts";')
    expect(sidebar).toContainSource('(e: \'focusSubjectContext\' | \'openWorkspacePath\', payload: string): void')
    expect(sidebar).toContainSource('@click="emit(\'openWorkspacePath\', schemaSourcePath)"')
    expect(sidebar).toContainSource('@click="emit(\'openWorkspacePath\', calendarSourcePath)"')
    expect(sidebar).toContainSource('function subjectSystemFilePath')
    expect(sidebar).toContainSource('function openSubjectSystemFile')
    expect(sidebar).toContainSource('title="打开 subject.md"')
    expect(sidebar).toContainSource('title="打开 events.jsonl"')
    expect(sidebar).toContainSource('title="打开 memory.jsonl"')
    expect(sidebar).toContainSource('title="打开 state.md"')
    expect(sidebar).toContainSource('{{ schemaSourcePath }}')
    expect(sidebar).toContainSource('{{ calendarSourcePath }}')
    expect(sidebar).toContainSource('Subjects')
    expect(sidebar).toContainSource('focusedSubjectId?: string;')
    expect(sidebar).toContainSource('(e: \'clearSubjectContext\' | \'toggleCollapsed\'): void')
    expect(sidebar).toContainSource('function clearSubjectContext(): void')
    expect(sidebar).toContainSource('emit("clearSubjectContext");')
    expect(sidebar).toContainSource('清语境')
    expect(sidebar).toContainSource('语境中')
    expect(sidebar).toContainSource(':aria-pressed="activeSubjectContextId === subject.id"')
    expect(sidebar).toContainSource('清空主体文件建议语境，不改变 timeline 过滤')
    expect(sidebar).toContainSource('FormSelect')
    expect(sidebar).toContainSource('<FormSelect v-model="selectedType"')
    expect(sidebar).not.toContainSource('<select v-model="selectedType"')
    expect(sidebar).toContainSource('toggleSubject')
    expect(sidebar).toContainSource('整体世界')
    expect(sidebar).toContainSource('清空过滤')
    expect(sidebar).toContainSource('toggleCollapsed')
    expect(sidebar).not.toContainSource('py-3 pr-11')
    expect(sidebar).toContainSource('resetKey')
    expect(sidebar).toContainSource('subjectStats')
    expect(sidebar).toContainSource('subjectStatMap')
    expect(sidebar).toContainSource('valueDraftSummaries')
    expect(sidebar).toContainSource('subjectDraftCountMap')
    expect(sidebar).toContainSource('draftSubjectCount')
    expect(sidebar).toContainSource('subjectDraftCount')
    expect(sidebar).toContainSource('activeSubjectCount')
    expect(sidebar).toContainSource('openReviewSubjectCount')
    expect(sidebar).toContainSource('doneReviewSubjectCount')
    expect(sidebar).toContainSource('world-sidebar-collapsed-summary')
    expect(sidebar).toContainSource('useResizablePanel')
    expect(sidebar).toContainSource('resizeHandleRef')
    expect(sidebar).toContainSource('panelStyle')
    expect(sidebar).toContainSource('isResizing')
    expect(sidebar).toContainSource('update:width')
    expect(sidebar).toContainSource('props.width')
    expect(sidebar).toContainSource('minSize: 220')
    expect(sidebar).toContainSource('maxSize: 420')
    expect(sidebar).toContainSource('edge: "right"')
    expect(sidebar).toContainSource('onResize: width => emit(\'update:width\', width)')
    expect(sidebar).toContainSource('onResizeEnd: width => emit(\'update:width\', width)')
    expect(sidebar).toContainSource('worldEngine.workbenchPreview.activeSubjects')
    expect(sidebar).toContainSource('worldEngine.workbenchPreview.selectedSubjects')
    expect(sidebar).toContainSource('worldEngine.workbenchPreview.subjectsWithOpenReviewIssues')
    expect(sidebar).toContainSource('worldEngine.workbenchPreview.subjectsWithValueDrafts')
    expect(sidebar).toContainSource('SubjectReviewFilter')
    expect(sidebar).toContainSource('SegmentedControl')
    expect(sidebar).toContainSource('subjectReviewFilterOptions')
    expect(sidebar).toContainSource('updateSubjectReviewFilter')
    expect(sidebar).toContainSource('subjectReviewFilter')
    expect(sidebar).toContainSource('matchesReviewFilter')
    expect(sidebar).toContainSource('setSubjectReviewFilter')
    expect(sidebar).toContainSource('clearSubjectReviewFilter')
    expect(sidebar).toContainSource('subjectReviewFilterLabel')
    expect(sidebar).toContainSource('subjectReviewTitle')
    expect(sidebar).toContainSource(':model-value="subjectReviewFilter"')
    expect(sidebar).toContainSource(':options="subjectReviewFilterOptions"')
    expect(sidebar).toContainSource('size="xs"')
    expect(sidebar).toContainSource(':aria-pressed="selectedSubjectSet.has(subject.id)"')
    expect(sidebar).toContainSource('左栏筛选')
    expect(sidebar).toContainSource('latestTime')
    expect(sidebar).toContainSource('mutationCount')
    expect(sidebar).toContainSource('issueCount')
    expect(sidebar).toContainSource('openIssueCount')
    expect(sidebar).toContainSource('doneIssueCount')
    expect(sidebar).toContainSource('confirmedIssueCount')
    expect(sidebar).toContainSource('ignoredIssueCount')
    expect(sidebar).toContainSource('confirmed')
    expect(sidebar).toContainSource('ignored')
    expect(sidebar).toContainSource('active')
    expect(sidebar).toContainSource('open')
    expect(sidebar).toContainSource('done')
    expect(sidebar).toContainSource('draft')
    expect(sidebar).toContainSource('worldEngine.workbenchPreview.valueDraftSubjects')
    expect(sidebar).toContainSource('slice metadata 草稿请使用中间 timeline 的 draft 过滤')
    expect(sidebar).toContainSource('worldEngine.workbenchPreview.valueCountShort')
    expect(sidebar).toContainSource('worldEngine.workbenchPreview.valueDraftCountTitle')
    expect(sidebar).not.toContainSource('worldEngine.workbenchPreview.attrCount')
    expect(sidebar).toContainSource('\'border-[var(--we-border)] bg-[var(--we-bg-panel)] hover:border-[var(--we-border-strong)] hover:bg-[var(--we-bg-hover)]\'')
    expect(sidebar).not.toContainSource('\'border-transparent hover:border-[var(--we-border)] hover:bg-[var(--we-bg-hover)]\'')

    expect(sliceList).toContainSource('WorldWorkbenchPreviewSubjectFilterMode')
    expect(sliceList).toContainSource('WorldWorkbenchPreviewSliceHealthFilter')
    expect(sliceList).toContainSource('WorldWorkbenchPreviewReviewQueueItem')
    expect(sliceList).toContainSource('SegmentedControl')
    expect(sliceList).toContainSource('SegmentedControlOption')
    expect(sliceList).toContainSource('SegmentedControlValue')
    expect(sliceList).toContainSource('matchesWorkbenchPreviewSliceFilter')
    expect(sliceList).toContainSource('busy?: boolean;')
    expect(sliceList).toContainSource('updateSubjectFilterMode')
    expect(sliceList).toContainSource('updateSliceSearch')
    expect(sliceList).toContainSource('updateSliceKindFilter')
    expect(sliceList).toContainSource('updateSliceHealthFilter')
    expect(sliceList).toContainSource('disabled: props.busy')
    expect(sliceList).toContainSource('function clearKindAndHealthFilters(): void')
    expect(sliceList).toContainSource('function toggleMaintenanceSlices(): void')
    expect(sliceList).toContainSource('watch(filteredSlices, (nextSlices) => {\n    if (props.busy) {')
    expect(sliceList).toContainSource(':disabled="props.busy || !previousVisibleSlice"')
    expect(sliceList).toContainSource(':disabled="props.busy || !nextVisibleSlice"')
    expect(sliceList).toContainSource(':disabled="props.busy"')
    expect(sliceList).toContainSource('<FormInput :model-value="props.sliceSearch" type="search" :placeholder="t(\'worldEngine.workbenchPreview.searchSlicePlaceholder\')" :disabled="props.busy"')
    expect(sliceList).toContainSource('resetKey')
    expect(sliceList).toContainSource('sliceKindFilter')
    expect(sliceList).toContainSource('sliceHealthFilter')
    expect(sliceList).toContainSource('showMaintenanceSlices')
    expect(sliceList).toContainSource('hiddenMaintenanceSliceCount')
    expect(sliceList).toContainSource('slice-list-maintenance-toggle')
    expect(sliceList).toContainSource('维护切片')
    expect(sliceList).toContainSource('isWorldWorkbenchSubjectSystemMaintenanceSlice')
    expect(sliceList).toContainSource('sliceReviewSummaryMap')
    expect(sliceList).toContainSource('reviewQueueItemsBySlice')
    expect(sliceList).toContainSource('focusReviewIssue')
    expect(sliceList).toContainSource('metadataDraftSummaries')
    expect(sliceList).toContainSource('metadataDraftCountMap')
    expect(sliceList).toContainSource('metadataDraftSummaryMap')
    expect(sliceList).toContainSource('metadata-draft-count')
    expect(sliceList).toContainSource('metadata-draft-summary')
    expect(sliceList).toContainSource('valueDraftSummaries')
    expect(sliceList).toContainSource('valueDraftCountMap')
    expect(sliceList).toContainSource('value-draft-count')
    expect(sliceList).toContainSource('draftCountForSlice')
    expect(sliceList).toContainSource('任一 subject')
    expect(sliceList).toContainSource('全部 subject')
    expect(sliceList).toContainSource('activeFilterChips')
    expect(sliceList).toContainSource('WorkbenchPreviewFilterChip')
    expect(sliceList).toContainSource('WorkbenchPreviewResultStats')
    expect(sliceList).toContainSource('WorkbenchPreviewDraftQueueItem')
    expect(sliceList).toContainSource('draftQueueItems')
    expect(sliceList).toContainSource('focusDraftQueueItem')
    expect(sliceList).toContainSource('showDraftSlices')
    expect(sliceList).toContainSource('openInspectorPanel: (target?: "subject-file-proposals") => void;')
    expect(sliceList).toContainSource('openSubjectFileProposals(sliceId: string, subjectId: string)')
    expect(sliceList).toContainSource('emit("focusSubject", subjectId);')
    expect(sliceList).toContainSource('props.openInspectorPanel("subject-file-proposals");')
    expect(sliceList).toContainSource('openDraftInspector')
    expect(sliceList).toContainSource('expandDraftEditor')
    expect(sliceList).toContainSource('subjectSystemSummaries?: WorldWorkbenchPreviewSubjectSystemSummary[]')
    expect(sliceList).toContainSource(':subject-system-summaries="props.subjectSystemSummaries ?? []"')
    expect(sliceList).toContainSource('Draft Queue')
    expect(sliceList).toContainSource('slice-list-draft-queue')
    expect(sliceList).toContainSource('slice-list-draft-queue-item')
    expect(sliceList).toContainSource('查看草稿切片')
    expect(sliceList).toContainSource('清空 search / kind / subject 过滤')
    expect(sliceList).toContainSource('displayTitle')
    expect(sliceList).toContainSource('displayTime')
    expect(sliceList).toContainSource('preview')
    expect(sliceList).toContainSource('metadataDraftCount')
    expect(sliceList).toContainSource('valueDraftCount')
    expect(sliceList).toContainSource('collectResultStats')
    expect(sliceList).toContainSource('statusShortcutSlices')
    expect(sliceList).toContainSource('statusShortcutStats')
    expect(sliceList).toContainSource('sliceHealthFilter: "all"')
    expect(sliceList).toContainSource('kindShortcutSlices')
    expect(sliceList).toContainSource('kindShortcutCountMap')
    expect(sliceList).toContainSource('subjectFilterModeOptions')
    expect(sliceList).toContainSource('kindFilterOptions')
    expect(sliceList).toContainSource('statusFilterOptions')
    expect(sliceList).toContainSource('sliceKindFilter: "all"')
    expect(sliceList).toContainSource('data-testid="slice-list-filter-toolbar"')
    expect(sliceList).toContainSource('rounded-md border border-[var(--we-border)] bg-[var(--we-bg-subtle)] px-2 py-1.5')
    expect(sliceList).toContainSource('font-mono text-[10px] uppercase tracking-[0.12em]')
    expect(sliceList).toContainSource('statusShortcutStats.value.openSlices')
    expect(sliceList).toContainSource('statusShortcutStats.value.doneSlices')
    expect(sliceList).toContainSource('statusShortcutStats.value.cleanSlices')
    expect(sliceList).toContainSource('statusShortcutStats.value.draftSlices')
    expect(sliceList).toContainSource('scopeLabel')
    expect(sliceList).toContainSource('currentVisibleSliceIndex')
    expect(sliceList).toContainSource('previousVisibleSlice')
    expect(sliceList).toContainSource('nextVisibleSlice')
    expect(sliceList).toContainSource('visibleSlicePositionLabel')
    expect(sliceList).toContainSource('navigateVisibleSlice')
    expect(sliceList).toContainSource('上一个可见切片')
    expect(sliceList).toContainSource('下一个可见切片')
    expect(sliceList).toContainSource('handleFilterChipAction')
    expect(sliceList).toContainSource(':model-value="props.sliceKindFilter"')
    expect(sliceList).toContainSource(':options="kindFilterOptions"')
    expect(sliceList).toContainSource(':model-value="props.sliceHealthFilter"')
    expect(sliceList).toContainSource(':options="statusFilterOptions"')
    expect(sliceList).toContainSource('kindShortcutCountMap.value.get(kind) ?? 0')
    expect(sliceList).toContainSource(':model-value="props.subjectFilterMode"')
    expect(sliceList).toContainSource(':options="subjectFilterModeOptions"')
    expect(sliceList).toContainSource('shortChipValue')
    expect(sliceList).toContainSource('当前筛选')
    expect(sliceList).not.toContainSource('worldEngine.workbenchPreview.visibleSlices')
    expect(sliceList).not.toContainSource('worldEngine.workbenchPreview.subjectsTouched')
    expect(sliceList).not.toContainSource('worldEngine.workbenchPreview.openSlicesIssues')
    expect(sliceList).not.toContainSource('slice-stat-open-filter')
    expect(sliceList).not.toContainSource('slice-stat-done-filter')
    expect(sliceList).not.toContainSource('slice-stat-clean-filter')
    expect(sliceList).not.toContainSource('slice-stat-draft-filter')
    expect(sliceList).toContainSource('只看仍有 open issue 的切片')
    expect(sliceList).toContainSource('只看 review 已处理完成的切片')
    expect(sliceList).toContainSource('只看没有派生 issue 的 clean 切片')
    expect(sliceList).toContainSource('只看有未应用草稿的切片')
    expect(sliceList).toContainSource('drafts')
    expect(sliceList).toContainSource('整体世界')
    expect(sliceList).toContainSource('单 subject')
    expect(sliceList).toContainSource('多 subject')
    expect(sliceList).toContainSource('data-testid="slice-list-clear-subject-filter-top"')
    expect(sliceList).toContainSource('清空 subject 过滤，回到整体世界时间线')
    expect(sliceList).toContainSource('worldEngine.workbenchPreview.subjectMode')
    expect(sliceList).toContainSource('匹配任一')
    expect(sliceList).toContainSource('匹配全部')
    expect(sliceList).toContainSource('open')
    expect(sliceList).toContainSource('done')
    expect(sliceList).toContainSource('clean')
    expect(sliceList).toContainSource('selectedSubjectFilters')
    expect(sliceList).toContainSource('removeSubjectFilter')
    expect(sliceList).toContainSource('恢复完整时间线')
    expect(sliceList).not.toContainSource('relative space-y-3 pl-7')
    expect(sliceList).not.toContainSource('absolute bottom-3 left-3 top-3 w-px')
    expect(sliceList).not.toContainSource('absolute -left-[22px] top-8')
    expect(sliceCard).toContainSource('patchGroups')
    expect(sliceCard).toContainSource('data-testid="world-slice-card"')
    expect(sliceCard).not.toContainSource('data-testid="world-slice-select-button"')
    expect(sliceCard).toContainSource('metadataDraftCount')
    expect(sliceCard).toContainSource('metadataDraftSummary')
    expect(sliceCard).toContainSource('hasMetadataDraft')
    expect(sliceCard).toContainSource('meta draft')
    expect(sliceCard).toContainSource('未应用 metadata 草稿')
    expect(sliceCard).toContainSource('metadataDraftDiffLabel')
    expect(sliceCard).toContainSource('displayTitle')
    expect(sliceCard).toContainSource('已应用')
    expect(sliceCard).toContainSource('valueDraftCount')
    expect(sliceCard).toContainSource('hasValueDraft')
    expect(sliceCard).toContainSource('value draft {{ props.valueDraftCount }}')
    expect(sliceCard).toContainSource('未应用 value 草稿')
    expect(sliceCard).not.toContainSource('选择切片')
    expect(sliceCard).toContainSource('sliceReviewSummary')
    expect(sliceCard).toContainSource('reviewItems')
    expect(sliceCard).toContainSource('visibleReviewItems')
    expect(sliceCard).toContainSource('hiddenReviewItemCount')
    expect(sliceCard).toContainSource('data-testid="slice-card-issue-row"')
    expect(sliceCard).toContainSource('buildWorldWorkbenchSubjectFileProposals')
    expect(sliceCard).toContainSource('const subjectFileProposals = computed(() => buildWorldWorkbenchSubjectFileProposals')
    expect(sliceCard).toContainSource('subjectFileProposalCount')
    expect(sliceCard).toContainSource('(e: "openSubjectFileProposals", sliceId: string, subjectId: string): void;')
    expect(sliceCard).toContainSource('function openSubjectFileProposals(): void')
    expect(sliceCard).toContainSource('emit("openSubjectFileProposals", props.slice.id, subjectFileProposals.value[0]?.subjectId ?? "");')
    expect(sliceCard).toContainSource('data-testid="slice-card-subject-file-proposal-count"')
    expect(sliceCard).toContainSource('type="button"')
    expect(sliceCard).toContainSource('@click.stop="openSubjectFileProposals"')
    expect(sliceCard).toContainSource('files {{ subjectFileProposalCount }}')
    expect(sliceCard).toContainSource('按当前主体语境，当前切片有主体文件建议')
    expect(sliceCard).toContainSource('focusReviewIssue')
    expect(sliceCard).toContainSource('worldWorkbenchIssueLevel')
    expect(sliceCard).toContainSource('worldWorkbenchIssueStatusLabel')
    expect(realUtil).toContainSource('export function worldWorkbenchIssueLevel')
    expect(realUtil).toContainSource('export function worldWorkbenchIssueStatusLabel')
    expect(realUtil).toContainSource('severity === "advisory"')
    expect(realUtil).not.toContainSource('code === "base-shifted" || code === "masked"')
    expect(sliceCard).toContainSource('reviewBadgeLabel')
    expect(sliceCard).toContainSource('hasOpenIssues')
    expect(sliceCard).toContainSource('按 subject 分组')
    expect(sliceCard).toContainSource('props.slice.title')
    expect(sliceCard).toContainSource('props.slice.summary')
    expect(sliceCard).toContainSource('props.slice.kind')
    expect(sliceCard).toContainSource('const opLabels: Record<string, string>')
    expect(sliceCard).toContainSource('append: "追加"')
    expect(sliceCard).toContainSource('increment: "增减"')
    expect(sliceCard).toContainSource('remove: "移除"')
    expect(sliceCard).toContainSource('replace: "设置"')
    expect(sliceCard).toContainSource('function opLabel(op: string): string')
    expect(sliceCard).toContainSource('formatWorkbenchPreviewValue')
    expect(sliceCard).toContainSource('function patchValueLabel(mutation: WorldWorkbenchPreviewSubjectGroup["mutations"][number]): string')
    expect(sliceCard).toContainSource('xl:grid-cols-[184px_minmax(0,1fr)]')
    expect(sliceCard).toContainSource('(e: \'select\' | \'focusSubject\' | \'filterSubject\' | \'insertSliceBefore\' | \'insertSliceAfter\', sliceId: string): void')
    expect(sliceCard).toContainSource('function insertSliceBefore(): void')
    expect(sliceCard).toContainSource('function insertSliceAfter(): void')
    expect(sliceCard).toContainSource('在此 Slice 之前插入新 Slice')
    expect(sliceCard).toContainSource('在此 Slice 之后插入新 Slice')
    expect(sliceCard).toContainSource('i-lucide-arrow-up-to-line')
    expect(sliceCard).toContainSource('i-lucide-arrow-down-to-line')
    expect(sliceCard).toContainSource('@click.stop="insertSliceBefore"')
    expect(sliceCard).toContainSource('@click.stop="insertSliceAfter"')
    expect(sliceCard).toContainSource('grid-cols-[minmax(88px,0.56fr)_44px_minmax(96px,1.65fr)_minmax(0,0.72fr)]')
    expect(sliceCard).toContainSource('{{ mutation.path }}')
    expect(sliceCard).toContainSource('{{ opLabel(mutation.op) }}')
    expect(sliceCard).toContainSource('{{ mutation.summary ?? "" }}')
    expect(sliceCard).toContainSource(':title="patchValueLabel(mutation)"')
    expect(sliceCard).toContainSource('{{ patchValueLabel(mutation) }}')
    expect(sliceCard).toContainSource('maxVisiblePatchesPerSubject = 6')
    expect(sliceCard).toContainSource('visiblePatches(group)')
    expect(sliceCard).toContainSource('hiddenPatchCount(group)')
    expect(sliceCard).toContainSource('+{{ hiddenPatchCount(group) }} patches')
    expect(sliceCard).toContainSource('role="button"')
    expect(sliceCard).toContainSource('tabindex="0"')
    expect(sliceCard).toContainSource('@click.stop="focusSubject(group.subjectId)"')
    expect(sliceCard).toContainSource('@keydown.enter.stop.prevent="focusSubject(group.subjectId)"')
    expect(sliceCard).toContainSource('@keydown.space.stop.prevent="focusSubject(group.subjectId)"')
    expect(sliceList).toContainSource('(e: \'selectSlice\' | \'focusSubject\' | \'filterSubject\' | \'removeSubjectFilter\' | \'insertSliceBefore\' | \'insertSliceAfter\' | \'updateSliceKindFilter\' | \'updateSliceSearch\', sliceId: string): void')
    expect(sliceList).toContainSource('@insert-slice-before="emit(\'insertSliceBefore\', $event)"')
    expect(sliceList).toContainSource('@insert-slice-after="emit(\'insertSliceAfter\', $event)"')
    expect(workbenchDialog).toContainSource('type SliceComposerInsertContext')
    expect(workbenchDialog).toContainSource('const sliceComposerInsertContext = ref<SliceComposerInsertContext | null>(null);')
    expect(workbenchDialog).toContainSource('function openSliceComposerAroundSlice(sliceId: string, direction: "before" | "after"): void')
    expect(workbenchDialog).toContainSource('@insert-slice-before="openSliceComposerAroundSlice($event, \'before\')"')
    expect(workbenchDialog).toContainSource('@insert-slice-after="openSliceComposerAroundSlice($event, \'after\')"')
    expect(workbenchDialog).toContainSource(':insert-slice-context="sliceComposerInsertContext"')
    expect(sliceComposer).toContainSource('suggestAdjacentPreviewTime')
    expect(sliceComposer).toContainSource('insertSliceContext?: {')
    expect(sliceComposer).toContainSource('return suggestAdjacentPreviewTime(examples, usedTimes, context.anchorTime, context.direction);')

    expect(inspector).toContainSource('worldEngine.workbenchPreview.sliceContext')
    expect(zhLocale).toContainSource('sliceContext')
    expect(enLocale).toContainSource('sliceContext')
    expect(inspector).toContainSource('focusedSubjectId')
    expect(inspector).toContainSource('focusSubject')
    expect(inspector).toContainSource('FormInput')
    expect(inspector).toContainSource('FormSelect')
    expect(inspector).toContainSource('FormTextarea')
    expect(inspector).toContainSource('busy?: boolean;')
    expect(inspector).toContainSource('discardDraftSliceId?: string;')
    expect(inspector).toContainSource('discardMetadataDraftForSlice')
    expect(inspector).toContainSource('backstory')
    expect(inspector).not.toContainSource(removedToken('cor', 'rection'))
    expect(inspector).toContainSource('应用到预览')
    expect(inspector).toContainSource('metadataDraftDirty')
    expect(inspector).toContainSource('metadataDrafts')
    expect(inspector).toContainSource('persistMetadataDraft')
    expect(inspector).toContainSource('persistMetadataDraft(previousSliceId, {')
    expect(inspector).toContainSource('baseline: WorldWorkbenchPreviewSlicePatch')
    expect(inspector).toContainSource('resetMetadataDrafts')
    expect(inspector).toContainSource('metadataDraftStatusLabel')
    expect(inspector).not.toContainSource('MetadataDraftDiffRow')
    expect(inspector).not.toContainSource('metadataDraftDiffRows')
    expect(inspector).not.toContainSource('metadata-draft-diff')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.metadataDraftDiff')
    expect(inspector).toContainSource('metadataDraftSummaries')
    expect(inspector).toContainSource('WorldWorkbenchPreviewMetadataDraftSummary')
    expect(inspector).toContainSource('draftTitle')
    expect(inspector).toContainSource('updateMetadataDrafts')
    expect(inspector).toContainSource('resetDraft')
    expect(inspector).toContainSource('if (props.busy || !metadataDraftDirty.value) {')
    expect(inspector).toContainSource('<FormInput v-model="draft.time" :disabled="props.busy" />')
    expect(inspector).toContainSource('<FormSelect v-model="draft.kind" :options="kindOptions" :disabled="props.busy" />')
    expect(inspector).toContainSource('<FormTextarea v-model="draft.summary" :rows="4" :disabled="props.busy" />')
    expect(inspector).toContainSource(':disabled="props.busy || !metadataDraftDirty"')
    expect(inspector).toContainSource('未应用修改')
    expect(inspector).toContainSource('已同步')
    expect(inspector).toContainSource('还原')
    expect(inspector).toContainSource('useResizablePanel')
    expect(inspector).toContainSource('resizeHandleRef')
    expect(inspector).toContainSource('panelStyle')
    expect(inspector).toContainSource('isResizing')
    expect(inspector).toContainSource('props.width')
    expect(inspector).toContainSource('update:width')
    expect(inspector).toContainSource('minSize: 300')
    expect(inspector).toContainSource('maxSize: 560')
    expect(inspector).toContainSource('edge: "left"')
    expect(inspector).toContainSource('onResize: width => emit(\'update:width\', width)')
    expect(inspector).toContainSource('onResizeEnd: width => emit(\'update:width\', width)')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.reviewIssues')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.reviewQueue')
    expect(inspector).toContainSource('flex min-h-0 flex-1 flex-col gap-3')
    expect(inspector).not.toContainSource('subject-system-summary')
    expect(inspector).toContainSource('order-6 rounded-md')
    expect(inspector).not.toContainSource('Subject System')
    expect(inspector).not.toContainSource('来自 simulation/subjects 的真实主体系统摘要')
    expect(inspector).not.toContainSource('path only')
    expect(inspector).toContainSource('subject-file-proposals')
    expect(inspector).toContainSource('subjectFileProposalFocusVersion?: number;')
    expect(inspector).toContainSource('const subjectFileProposalsRef = ref<HTMLElement | null>(null);')
    expect(inspector).toContainSource('function scrollSubjectFileProposalsIntoView(): Promise<void>')
    expect(inspector).toContainSource('subjectFileProposalsRef.value?.scrollIntoView({block: "start"});')
    expect(inspector).toContainSource('watch(() => props.subjectFileProposalFocusVersion')
    expect(inspector).toContainSource('ref="subjectFileProposalsRef"')
    expect(inspector).toContainSource('subjectFileProposalCount')
    expect(inspector).toContainSource('data-testid="subject-file-proposal-count"')
    expect(inspector).toContainSource('仅生成建议，不会自动写入 simulation/subjects')
    expect(inspector).toContainSource('proposal.eventJsonLine')
    expect(inspector).toContainSource('proposal.memoryJsonLines')
    expect(inspector).toContainSource('(e: "commitSubjectEventProposal", proposal: WorldWorkbenchSubjectFileProposal): void;')
    expect(inspector).toContainSource('committedSubjectEventKeys?: string[];')
    expect(inspector).toContainSource('committedSubjectEventKeySet')
    expect(inspector).toContainSource('worldWorkbenchSubjectEventProposalKey(proposal)')
    expect(inspector).toContainSource('这条 events.jsonl 经历已在当前会话处理。')
    expect(inspector).toContainSource('function commitSubjectEventProposal(proposal: WorldWorkbenchSubjectFileProposal): void')
    expect(inspector).toContainSource('emit("commitSubjectEventProposal", proposal);')
    expect(inspector).toContainSource('确认后追加到 events.jsonl')
    expect(inspector).toContainSource('已追加')
    expect(inspector).toContainSource('追加')
    expect(inspector).toContainSource('proposal.sourceKind === \'direct-mutation\'')
    expect(inspector).toContainSource('proposal.sourceLabel')
    expect(inspector).toContainSource('function copyAllSubjectFileProposals(): Promise<void>')
    expect(inspector).toContainSource('join("\\n\\n---\\n\\n")')
    expect(inspector).toContainSource('title="复制全部主体文件建议"')
    expect(inspector).toContainSource('全部主体文件建议已复制。')
    expect(inspector).toContainSource('function copySubjectFileProposalText(text: string, successMessage: string): Promise<boolean>')
    expect(inspector).toContainSource('notification.error("复制失败，请手动选择文本后复制。");')
    expect(inspector).toContainSource('function copySubjectFileProposalTextAndOpen(text: string, successMessage: string, path: string): Promise<void>')
    expect(inspector).toContainSource('World Engine 工作台正在同步，请稍候再打开目标文件。')
    expect(inspector).toContainSource('目标文件路径为空，无法打开。')
    expect(inspector).toContainSource('if (copied) {')
    expect(inspector).toContainSource('openSubjectFileProposalPath(path);')
    expect(inspector).toContainSource('title="复制 events.jsonl 行"')
    expect(inspector).toContainSource('title="复制 events.jsonl 行并打开文件，确认后追加到文件末尾"')
    expect(inspector).toContainSource('title="复制 memory.jsonl 候选行"')
    expect(inspector).toContainSource('title="复制 memory.jsonl 候选行并打开文件，确认后追加新行或按 topic 改写"')
    expect(inspector).toContainSource('title="复制 state.md 审查提示"')
    expect(inspector).toContainSource('title="复制 state.md 审查提示并打开文件，打开后检查对应区块"')
    expect(inspector).toContainSource('复制并打开')
    expect(inspector).toContainSource('events.jsonl 行已复制，打开文件后确认并追加到末尾。')
    expect(inspector).toContainSource('proposal.stateReviewReasons.join(\'\\n\')')
    expect(inspector).toContainSource('state.md 审查提示已复制。')
    expect(inspector).toContainSource('写入前确认第一人称口吻、角色当时知道什么；确认后追加到 events.jsonl 末尾。')
    expect(inspector).toContainSource('memory.jsonl 候选行已复制，打开文件后确认追加新行或按 topic 改写。')
    expect(inspector).toContainSource('memory.jsonl 是当前认知快照；写入前确认追加新行，还是按 topic 改写已有行。')
    expect(inspector).toContainSource('state.md 审查提示已复制，打开文件后检查对应区块。')
    expect(inspector).toContainSource('(e: \'focusSubject\' | \'openWorkspacePath\', payload: string): void')
    expect(inspector).toContainSource('function openSubjectFileProposalPath(path: string): void')
    expect(inspector).toContainSource('title="打开 events.jsonl"')
    expect(inspector).toContainSource('title="打开 memory.jsonl"')
    expect(inspector).toContainSource('title="打开 state.md"')
    expect(inspector).toContainSource('order-7 flex flex-col gap-2')
    expect(inspector).not.toContainSource('reviewQueueItems')
    expect(inspector).not.toContainSource('reviewTriageSummary')
    expect(inspector).not.toContainSource('reviewQueueMode')
    expect(inspector).not.toContainSource('updateReviewQueueMode')
    expect(inspector).not.toContainSource('visibleReviewQueueItems')
    expect(inspector).not.toContainSource('activeVisibleQueueIndex')
    expect(inspector).not.toContainSource('currentIssueOutsideVisibleQueue')
    expect(inspector).not.toContainSource('currentReviewQueueItem')
    expect(inspector).not.toContainSource('updateIssueTriage')
    expect(inspector).not.toContainSource('IssueTriageOption')
    expect(inspector).not.toContainSource('issueTriageOptions')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.triageProgress')
    expect(inspector).not.toContainSource('currentReviewQueueIndex')
    expect(inspector).not.toContainSource('previousReviewQueueItem')
    expect(inspector).not.toContainSource('nextReviewQueueItem')
    expect(inspector).not.toContainSource('focusReviewQueueItem')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.onlyOpen')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.allIssues')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.openQueueClear')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.previousOpen')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.nextOpen')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.previousIssue')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.nextIssue')
    expect(inspector).not.toContainSource('issueLevel')
    expect(inspector).toContainSource('props.slice.time')
    expect(inspector).toContainSource('props.slice.title')
    expect(inspector).toContainSource('props.slice.summary')
    expect(inspector).toContainSource('props.slice.kind')
    expect(inspector).not.toContainSource('base-shifted')
    expect(inspector).not.toContainSource('masked')
    expect(inspector).toContainSource('worldEngine.workbenchPreview.stateSnapshot')
    expect(inspector).toContainSource('JsonViewer')
    expect(inspector).toContainSource('nbook/app/components/common/JsonViewer.vue')
    expect(inspector).toContainSource('rawSnapshotValue')
    expect(inspector).toContainSource('<JsonViewer :value="rawSnapshotValue" :max-height="400" />')
    expect(inspector).not.toContainSource('SnapshotTreeNode')
    expect(inspector).not.toContainSource('SnapshotTreeView')
    expect(inspector).not.toContainSource('snapshotTreeNodes')
    expect(inspector).not.toContainSource('buildSnapshotTreeNode')
    expect(inspector).not.toContainSource('snapshot-tree-node')
    expect(inspector).not.toContainSource('rawSnapshotJson')
    expect(inspector).not.toContainSource('<pre class="max-h-72')
    expect(inspector).toContainSource('完整世界')
    expect(inspector).toContainSource('只看触及主体')
    expect(inspector).toContainSource(':aria-pressed="showFullState"')
    expect(inspector).not.toContainSource('worldEngine.workbenchPreview.schemaExcerpt')

    expect(editor).toContainSource('worldEngine.workbenchPreview.reviewWorkbench')
    expect(editor).toContainSource('审查工作台')
    expect(editor).not.toContainSource('Mutation Editor')
    expect(editor).not.toContainSource('变更编辑器')
    expect(editor).toContainSource('JsonViewer')
    expect(editor).toContainSource('nbook/app/components/common/JsonViewer.vue')
    expect(editor).toContainSource('<JsonViewer v-if="activeSubjectState" class="min-h-0 flex-1" :value="activeSubjectState.attrs" :main-menu-bar="false" :max-height="0" />')
    expect(editor).not.toContainSource('stateRows')
    expect(editor).not.toContainSource('WorldWorkbenchPreviewAttrRow')
    expect(editor).toContainSource('useResizablePanel')
    expect(editor).toContainSource('resizeHandleRef')
    expect(editor).toContainSource('panelStyle')
    expect(editor).toContainSource('isResizing')
    expect(editor).toContainSource('props.height')
    expect(editor).toContainSource('update:height')
    expect(editor).toContainSource('minSize: 160')
    expect(editor).toContainSource('maxSize: 520')
    expect(editor).toContainSource('edge: "top"')
    expect(editor).toContainSource('onResize: height => emit(\'update:height\', height)')
    expect(editor).toContainSource('onResizeEnd: height => emit(\'update:height\', height)')
    expect(editor).toContainSource('SegmentedControl')
    expect(editor).toContainSource('SegmentedControlOption')
    expect(editor).toContainSource('SegmentedControlValue')
    expect(editor).toContainSource('editorViewOptions')
    expect(editor).toContainSource('reviewQueueModeOptions')
    expect(editor).toContainSource('subjectNavigationScopeOptions')
    expect(editor).toContainSource('updateEditorView')
    expect(editor).toContainSource('updateReviewQueueMode')
    expect(editor).toContainSource('updateSubjectNavigationScope')
    expect(editor).toContainSource('问题处理')
    expect(editor).toContainSource('Subject 视图')
    expect(editor).toContainSource('总变更')
    expect(editor).toContainSource(':model-value="view"')
    expect(editor).toContainSource(':options="editorViewOptions"')
    expect(editor).toContainSource('editorSummary')
    expect(editor).toContainSource('activeSubjectSummary')
    expect(editor).toContainSource('focusedSubjectId')
    expect(editor).toContainSource('highlightedMutationFocus')
    expect(editor).toContainSource('setActiveSubject')
    expect(editor).toContainSource('filteredTouchedSubjectIds')
    expect(editor).toContainSource('navigateSubjectSlice')
    expect(editor).toContainSource('SubjectNavigationScope')
    expect(editor).toContainSource('subjectNavigationScope')
    expect(editor).toContainSource('setSubjectNavigationScope')
    expect(editor).toContainSource('matchesNavigationScope')
    expect(editor).toContainSource('matchesWorkbenchPreviewSliceFilter')
    expect(editor).toContainSource('sliceReviewSummaryMap')
    expect(editor).toContainSource('sliceKindFilter')
    expect(editor).toContainSource('sliceHealthFilter')
    expect(editor).toContainSource('sliceSearch')
    expect(editor).toContainSource('relatedSlicePosition')
    expect(editor).toContainSource('subjectNavigationScopeLabel')
    expect(editor).toContainSource('subject 轨迹')
    expect(editor).toContainSource('过滤组合')
    expect(editor).toContainSource(':aria-pressed="activeSubjectId === subjectId"')
    expect(editor).toContainSource(':model-value="subjectNavigationScope"')
    expect(editor).toContainSource(':options="subjectNavigationScopeOptions"')
    expect(editor).toContainSource('previousRelatedSlice')
    expect(editor).toContainSource('nextRelatedSlice')
    expect(editor).toContainSource('valueDrafts')
    expect(editor).toContainSource('busy?: boolean;')
    expect(editor).toContainSource('discardDraftSliceId?: string;')
    expect(editor).toContainSource('discardValueDraftsForSlice')
    expect(editor).toContainSource('resetKey')
    expect(editor).toContainSource('resetAllValueDrafts')
    expect(editor).toContainSource('requestResetAllValueDrafts')
    expect(editor).toContainSource('if (props.busy)')
    expect(editor).toContainSource('const key = valueDraftKey(index);')
    expect(editor).toContainSource('hasValueDraft')
    expect(editor).toContainSource('ValueDraftSummary')
    expect(editor).toContainSource('allDirtyValueDrafts')
    expect(editor).toContainSource('allDirtyValueDraftCount')
    expect(editor).toContainSource('otherSliceDirtyDrafts')
    expect(editor).toContainSource('otherSliceDirtyDraftCount')
    expect(editor).toContainSource('nextOtherSliceDraft')
    expect(editor).toContainSource('navigateToOtherDraft')
    expect(editor).toContainSource('valueDraftKeyForSlice')
    expect(editor).toContainSource('其他切片')
    expect(editor).toContainSource('跳到草稿')
    expect(editor).toContainSource('清空草稿')
    expect(editor).toContainSource('data-testid="mutation-editor-next-draft-slice"')
    expect(editor).toContainSource('data-testid="mutation-editor-clear-all-drafts"')
    expect(editor).toContainSource('data-testid="mutation-editor-next-draft-toolbar"')
    expect(editor).toContainSource('data-testid="mutation-editor-clear-all-drafts-toolbar"')
    expect(editor).toContainSource('data-testid="world-review-panel"')
    expect(editor).toContainSource('reviewPanelStyle')
    expect(editor).toContainSource('height: "40px"')
    expect(editor).toContainSource('transition-[height] duration-300')
    expect(editor).toContainSource('class="flex min-h-0 flex-1 flex-col overflow-hidden px-3 py-3"')
    expect(editor).toContainSource('class="min-h-0 flex-1 space-y-3 overflow-y-auto custom-scrollbar"')
    expect(editor).toContainSource('class="grid min-h-0 flex-1 gap-3 xl:grid-cols-[240px_minmax(0,1fr)]"')
    expect(editor).toContainSource('class="flex min-h-0 flex-col overflow-hidden rounded-md border border-[var(--we-border)] bg-[var(--we-bg-subtle)] p-2.5"')
    expect(editor).toContainSource('class="min-h-0 flex-1 space-y-1 overflow-y-auto pr-1 custom-scrollbar"')
    expect(editor).toContainSource('class="grid min-h-0 flex-1 gap-3 2xl:grid-cols-2"')
    expect(editor).toContainSource('class="flex min-h-0 flex-col"')
    expect(editor).toContainSource('WorldEngineWorkbenchPreviewPatchEditor')
    expect(editor).toContainSource('activeSubjectPatchEditorRows')
    expect(patchEditor).toContainSource('class="min-h-0 flex-1 overflow-y-auto overflow-x-hidden flex flex-col gap-2 custom-scrollbar pr-1"')
    expect(patchEditor).toContainSource('主行编辑 patch 字段，次行编辑 summary')
    expect(patchEditor).toContainSource('data-testid="mutation-editor-row"')
    expect(patchEditor).toContainSource('class="flex flex-col gap-2 rounded-md border border-[var(--we-border)] p-2.5 text-[11px] transition-colors"')
    expect(patchEditor).toContainSource('class="flex min-w-0 flex-1 items-start gap-2"')
    expect(patchEditor).toContainSource('class="mt-0.5 flex shrink-0 items-center justify-end gap-0.5"')
    expect(patchEditor).toContainSource('FormSelect')
    expect(patchEditor).toContainSource('Combobox')
    expect(patchEditor).toContainSource('pathOptions')
    expect(patchEditor).toContainSource('(e: \'append\' | \'reset\' | \'save\' | \'submit\'): void')
    expect(patchEditor).toContainSource('@click="emit(\'append\')"')
    expect(patchEditor).toContainSource('@click="emit(\'save\')"')
    expect(patchEditor).toContainSource('@click="emit(\'reset\')"')
    expect(editor).toContainSource('@append="appendPatchDraft"')
    expect(editor).toContainSource('@save="savePatchDrafts"')
    expect(editor).toContainSource('@reset="resetPatchDrafts"')
    expect(editor).toContainSource(':dirty="patchDraftDirty"')
    expect(editor).toContainSource(':error="patchDraftError"')
    expect(patchEditor).toContainSource('<Combobox :model-value="row.mutation.path"')
    expect(patchEditor).toContainSource('<FormSelect :model-value="row.mutation.op"')
    expect(patchEditor).toContainSource('size="sm"')
    expect(patchEditor).not.toContainSource('>attr</span>')
    expect(patchEditor).not.toContainSource('>op</span>')
    expect(patchEditor).not.toContainSource('>value</span>')
    expect(patchEditor).not.toContainSource('attrSelectOptions')
    expect(patchEditor).not.toContainSource('pathDatalistId')
    expect(patchEditor).not.toContainSource('<input :value="row.mutation.path"')
    expect(patchEditor).not.toContainSource('<datalist')
    expect(patchEditor).not.toContainSource('<FormSelect :model-value="row.mutation.path"')
    expect(patchEditor).not.toContainSource('<select :value="row.mutation.op"')
    expect(patchEditor).not.toContainSource('切片前')
    expect(patchEditor).not.toContainSource('切片后')
    expect(editor).toContainSource('Transition name="world-review-panel-body"')
    expect(editor).toContainSource('.world-review-panel-body-enter-active')
    expect(editor).toContainSource('transform: translateY(8px)')
    expect(patchEditor).toContainSource('data-testid="mutation-editor-row"')
    expect(editor).toContainSource('data-testid="mutation-editor-apply-all-banner"')
    expect(editor).toContainSource('data-testid="mutation-editor-reset-all-banner"')
    expect(editor).toContainSource('dirtyMutationRows')
    expect(editor).toContainSource('dirtyValueDraftCount')
    expect(editor).toContainSource('valueDraftErrorCount')
    expect(editor).toContainSource('valueDraftStatusLabel')
    expect(editor).toContainSource('applyDirtyValueDrafts')
    expect(editor).toContainSource('resetDirtyValueDrafts')
    expect(editor).toContainSource(':disabled="props.busy || !dirtyValueDraftCount"')
    expect(editor).toContainSource(':disabled="props.busy || !isValueDraftDirty(row.index, row.mutation)"')
    expect(editor).toContainSource('parseDirtyValueDrafts')
    expect(editor).toContainSource('worldEngine.workbenchPreview.draftChanges')
    expect(editor).toContainSource('未应用')
    expect(editor).toContainSource('已同步')
    expect(editor).toContainSource('应用全部')
    expect(editor).toContainSource('还原全部')
    expect(editor).toContainSource('dirty')
    expect(editor).toContainSource('WorldEngineWorkbenchPreviewValueInput')
    expect(patchEditor).toContainSource('WorldEngineWorkbenchPreviewValueInput')
    expect(editor).toContainSource('parseWorkbenchPreviewMutationValue')
    expect(editor).toContainSource('parseMutationJson')
    expect(editor).toContainSource('opOptionsForPreviewAttr')
    expect(editor).toContainSource('resolvePreviewAttrPath')
    expect(editor).toContainSource('defaultMutationForPreviewSubject')
    expect(editor).toContainSource('defaultValueForPreviewAttr')
    expect(editor).toContainSource('updateMutationPatches')
    expect(editor).toContainSource('updateMutationValue')
    expect(editor).toContainSource('updateValueDrafts')
    expect(editor).toContainSource('patchDrafts')
    expect(editor).toContainSource('patchValueDrafts')
    expect(editor).toContainSource('patchDraftDirty')
    expect(editor).toContainSource('activeSubjectPatchDraftRows')
    expect(editor).toContainSource('activeSubjectPatchEditorRows')
    expect(editor).toContainSource('savePatchDrafts')
    expect(editor).toContainSource('resetPatchDrafts')
    expect(editor).toContainSource('appendPatchDraft')
    expect(editor).toContainSource('duplicatePatchDraft')
    expect(editor).toContainSource('deletePatchDraft')
    expect(editor).toContainSource('movePatchDraft')
    expect(editor).toContainSource('updatePatchDraftPath')
    expect(editor).toContainSource('updatePatchDraftOp')
    expect(editor).toContainSource('updatePatchValueDraft')
    expect(editor).toContainSource('updatePatchDraftSummary')
    expect(editor).toContainSource('path')
    expect(patchEditor).toContainSource('summary')
    expect(patchEditor).toContainSource('patch draft')
    expect(editor).toContainSource('previousSnapshotSubjects')
    expect(editor).toContainSource('mutationBeforeValue')
    expect(editor).toContainSource('mutationAfterValue')
    expect(editor).toContainSource('isHighlightedMutation')
    expect(editor).toContainSource('reviewFocusContext')
    expect(editor).not.toContainSource('Review Focus')
    expect(editor).toContainSource('reviewMutationContext')
    expect(editor).toContainSource('reviewIssueExplanation')
    expect(editor).toContainSource('MutationContextItem')
    expect(editor).toContainSource('MutationContextTriple')
    expect(editor).toContainSource('IssueExplanation')
    expect(editor).toContainSource('MutationContextExplanation')
    expect(editor).toContainSource('mutationTimelineForIssue')
    expect(editor).toContainSource('findCurrentMutationContext')
    expect(editor).toContainSource('attrPathRelated')
    expect(editor).toContainSource('same subject + attr path')
    expect(editor).toContainSource('data-testid="mutation-context"')
    expect(editor).toContainSource('data-testid="mutation-context-card"')
    expect(editor).toContainSource('前一个 mutation')
    expect(editor).toContainSource('当前 mutation')
    expect(editor).toContainSource('后一个 mutation')
    expect(editor).toContainSource('没有更早的相关 mutation')
    expect(editor).toContainSource('没有更晚的相关 mutation')
    expect(editor).toContainSource('context.explanation.whatHappened')
    expect(editor).toContainSource('context.explanation.whyItMatters')
    expect(editor).toContainSource('context.explanation.suggestedAction')
    expect(editor).not.toContainSource('buildIssueExplanation')
    expect(editor).toContainSource('buildMutationContextExplanation')
    expect(editor).toContainSource('这不是后端 issue，只是当前工作台的定位状态。')
    expect(editor).not.toContainSource('mutationContextBeforeValue')
    expect(editor).not.toContainSource('mutationContextAfterValue')
    expect(editor).not.toContainSource('snapshotSubjectsForSlice')
    expect(editor).not.toContainSource('previousSnapshotSubjectsForSlice')
    expect(editor).not.toContainSource('>before<')
    expect(editor).not.toContainSource('>after<')
    expect(editor).toContainSource('发生了什么')
    expect(editor).toContainSource('为什么要看')
    expect(editor).toContainSource('建议处理')
    expect(editor).toContainSource('动作')
    expect(editor).toContainSource('依赖/覆盖关系')
    expect(editor).toContainSource('为什么相关')
    expect(editor).toContainSource('需要确认')
    expect(editor).toContainSource('reviewFocusContext.label')
    expect(editor).toContainSource('{{ item.label }}')
    expect(editor).toContainSource('item.severity')
    expect(editor).not.toContainSource('A1（提醒）')
    expect(editor).not.toContainSource('A2（提醒）')
    expect(editor).not.toContainSource('E1（持久）')
    expect(editor).not.toContainSource('E2（持久）')
    expect(editor).not.toContainSource('code === "broken-relative"')
    expect(editor).not.toContainSource('code === "dangling-ref"')
    expect(editor).not.toContainSource('code === "base-shifted"')
    expect(editor).not.toContainSource('code === "masked"')
    expect(editor).toContainSource('mutationActionPhrase')
    expect(editor).toContainSource('mutationRelationText')
    expect(editor).toContainSource('mutationConfirmationText')
    expect(editor).toContainSource('mutationValueLabel')
    expect(editor).toContainSource('readableValue')
    expect(editor).toContainSource('incrementValuePhrase')
    expect(editor).not.toContainSource('relativeOperationQuestion')
    expect(editor).toContainSource('mutation.op === "replace"')
    expect(editor).toContainSource('mutation.op === "remove"')
    expect(editor).toContainSource('mutation.op === "increment"')
    expect(editor).toContainSource('使用 append')
    expect(editor).toContainSource('currentSliceReviewItems')
    expect(editor).toContainSource('worldWorkbenchIssueLevel')
    expect(editor).toContainSource('worldWorkbenchIssueStatusLabel')
    expect(editor).toContainSource('data-testid="mutation-editor-issue-row"')
    expect(editor).toContainSource('focusReviewIssue')
    expect(editor).toContainSource('updateIssueTriage')
    expect(editor).toContainSource('IssueTriageOption')
    expect(editor).toContainSource('issueTriageOptions')
    expect(editor).toContainSource(':aria-pressed="reviewFocusContext.status === option.status"')
    expect(editor).toContainSource('worldEngine.workbenchPreview.triageProgress')
    expect(editor).toContainSource('worldEngine.workbenchPreview.reviewQueueSummary')
    expect(editor).toContainSource('worldEngine.workbenchPreview.onlyOpen')
    expect(editor).toContainSource('worldEngine.workbenchPreview.allIssues')
    expect(editor).toContainSource('worldEngine.workbenchPreview.previousOpen')
    expect(editor).toContainSource('worldEngine.workbenchPreview.nextOpen')
    expect(editor).toContainSource('previousReviewQueueItem')
    expect(editor).toContainSource('nextReviewQueueItem')
    expect(editor).toContainSource('待处理')
    expect(editor).toContainSource('确认')
    expect(editor).toContainSource('忽略')
    expect(editor).toContainSource('clearReviewFocus')
    expect(editor).toContainSource('clearMutationFocus')
    expect(editor).toContainSource('清除定位')
    expect(editor).toContainSource('issue target')
    expect(editor).toContainSource('切片前')
    expect(editor).toContainSource('切片后')
    expect(editor).toContainSource('此时状态')
    expect(patchEditor).toContainSource('本切片变更')
    expect(valueInput).toContainSource('resolveInputKind')
    expect(valueInput).toContainSource('FormSelect')
    expect(valueInput).toContainSource('FormNumberInput')
    expect(valueInput).toContainSource('refSubjectType')
    expect(valueInput).toContainSource('v-else-if="inputKind === \'number\'"')
    expect(valueInput).toContainSource('inputKind === \'ref\'')
    expect(valueInput).toContainSource('inputKind === \'boolean\'')
    expect(valueInput).toContainSource('inputKind === \'enum\'')
    expect(valueInput).toContainSource('inputKind === \'json\'')
    expect(valueInput).toContainSource('size="sm"')
    expect(valueInput).not.toContainSource('<select')

    expect(types).toContainSource('WorldWorkbenchPreviewSlice')
    expect(types).toContainSource('WorldWorkbenchPreviewSnapshot')
    expect(types).toContainSource('WorldWorkbenchPreviewSlicePatch')
    expect(types).toContainSource('WorldWorkbenchPreviewMutationFocus')
    expect(types).toContainSource('WorldWorkbenchPreviewMutationValuePatch')
    expect(types).toContainSource('WorldWorkbenchPreviewMetadataDraftSummary')
    expect(types).toContainSource('draftTitle')
    expect(types).toContainSource('WorldWorkbenchPreviewValueDraftSummary')
    expect(types).toContainSource('WorldWorkbenchPreviewIssueStatus')
    expect(types).toContainSource('WorldWorkbenchPreviewIssueTriageState')
    expect(types).toContainSource('WorldWorkbenchPreviewIssueTriagePatch')
    expect(types).toContainSource('WorldWorkbenchPreviewIssueTriageSummary')
    expect(types).toContainSource('WorldWorkbenchPreviewSliceReviewSummary')
    expect(types).toContainSource('WorldWorkbenchPreviewReviewQueueItem')
    expect(types).toContainSource('WorldWorkbenchPreviewReviewQueueMode')
    expect(types).toContainSource('WorldWorkbenchPreviewSubjectFilterMode')
    expect(types).toContainSource('WorldWorkbenchPreviewSliceHealthFilter')
    expect(types).toContainSource('WorldWorkbenchPreviewSubjectStat')
    expect(types).toContainSource('openIssueCount')
    expect(types).toContainSource('doneIssueCount')
    expect(types).toContainSource('confirmedIssueCount')
    expect(types).toContainSource('ignoredIssueCount')
    expect(types).toContainSource('sourceKind: "direct-mutation" | "focused-world-context";')
    expect(types).toContainSource('sourceLabel: string;')
    expect(types).toContainSource('sliceId: string;')
    expect(types).toContainSource('sliceTime: string;')
    expect(types).toContainSource('sliceTitle: string;')
    expect(types).toContainSource('sliceKind: string;')
  })

  it('从 schema default 和 slices reduce 出稳定 mock snapshots', () => {
    const snapshots = reduceWorkbenchPreviewSnapshots(cloneMockWorkbenchSlices(), mockWorkbenchSubjects, mockWorkbenchSchema)

    expect(findSnapshotSubject(snapshots, 'slice-world-init', 'erina').attrs).toMatchObject({
      hp: 100,
      inventory: [],
      events: [],
    })
    expect(findSnapshotSubject(snapshots, 'slice-erina-arrives', 'erina').attrs.inventory).toEqual(['subject://old-sword'])
    expect(findSnapshotSubject(snapshots, 'slice-erina-arrives', 'old-sword').attrs.durability).toBe(95)
    expect(findSnapshotSubject(snapshots, 'slice-east-tower-opened', 'old-sword').attrs.durability).toBe(80)
    expect(findSnapshotSubject(snapshots, 'slice-old-sword-backstory', 'old-sword').attrs.durability).toBe(82)
    expect(findSnapshotSubject(snapshots, 'slice-erina-hands-sword', 'erina').attrs.inventory).toEqual([])
    expect(findSnapshotSubject(snapshots, 'slice-erina-hands-sword', 'moran').attrs.inventory).toEqual(['subject://old-sword'])
    expect(findSnapshotSubject(snapshots, 'slice-erina-hands-sword', 'old-sword').attrs.owner).toBe('subject://moran')
  })

  it('mock snapshot append 与运行时一致：普通 list 保留重复，collection 去重', () => {
    const slices: WorldWorkbenchPreviewSlice[] = [{
      id: 'slice-append-semantics',
      time: 'C01:00:01',
      title: 'append 语义检查',
      summary: '普通 list 与 collection 的 append 语义不同。',
      kind: 'event',
      mutations: [
        { subjectId: 'erina', path: '/events', op: 'append', value: '重复事件' },
        { subjectId: 'erina', path: '/events', op: 'append', value: '重复事件' },
        { subjectId: 'erina', path: '/inventory', op: 'append', value: 'subject://old-sword' },
        { subjectId: 'erina', path: '/inventory', op: 'append', value: 'subject://old-sword' },
      ],
    }]

    const snapshots = reduceWorkbenchPreviewSnapshots(slices, mockWorkbenchSubjects, mockWorkbenchSchema)
    const erina = findSnapshotSubject(snapshots, 'slice-append-semantics', 'erina')

    expect(erina.attrs.events).toEqual(['重复事件', '重复事件'])
    expect(erina.attrs.inventory).toEqual(['subject://old-sword'])
  })

  it('应用 mutation value patch 后重算 snapshots 且不会重复叠加相对 mutation', () => {
    const slices = cloneMockWorkbenchSlices()
    const namePatch = applyWorkbenchPreviewMutationPatch({
      schema: mockWorkbenchSchema,
      slices,
      subjects: mockWorkbenchSubjects,
      patch: {
        sliceId: 'slice-world-init',
        mutationIndex: 2,
        value: '新王都',
      },
    })
    expect(namePatch?.label).toBe('capital/name')
    expect(findSnapshotSubject(namePatch?.snapshots ?? [], 'slice-world-init', 'capital').attrs.name).toBe('新王都')
    expect(findSnapshotSubject(namePatch?.snapshots ?? [], 'slice-erina-arrives', 'capital').attrs.name).toBe('新王都')

    const durabilityPatch = applyWorkbenchPreviewMutationPatch({
      schema: mockWorkbenchSchema,
      slices,
      subjects: mockWorkbenchSubjects,
      patch: {
        sliceId: 'slice-erina-arrives',
        mutationIndex: 4,
        value: -10,
      },
    })
    expect(durabilityPatch?.label).toBe('old-sword/durability')
    expect(findSnapshotSubject(durabilityPatch?.snapshots ?? [], 'slice-erina-arrives', 'old-sword').attrs.durability).toBe(90)
    expect(findSnapshotSubject(durabilityPatch?.snapshots ?? [], 'slice-east-tower-opened', 'old-sword').attrs.durability).toBe(75)
    expect(findSnapshotSubject(durabilityPatch?.snapshots ?? [], 'slice-old-sword-backstory', 'old-sword').attrs.durability).toBe(82)
    expect(findSnapshotSubject(durabilityPatch?.snapshots ?? [], 'slice-erina-arrives', 'erina').attrs.inventory).toEqual(['subject://old-sword'])
  })

  it('应用 mutation list patch 后整块替换 slice mutations 并重算 snapshots', () => {
    const slices = cloneMockWorkbenchSlices()
    const result = applyWorkbenchPreviewMutationListPatch({
      schema: mockWorkbenchSchema,
      slices,
      subjects: mockWorkbenchSubjects,
      patch: {
        sliceId: 'slice-erina-arrives',
        patches: [
          { subjectId: 'erina', path: '/location', op: 'replace', value: 'subject://east-tower', summary: '改为东塔' },
          { subjectId: 'erina', path: '/events', op: 'append', value: '提前抵达东塔' },
        ],
      },
    })

    expect(result?.slices.find(slice => slice.id === 'slice-erina-arrives')?.mutations).toEqual([
      { subjectId: 'erina', path: '/location', op: 'replace', value: 'subject://east-tower', summary: '改为东塔' },
      { subjectId: 'erina', path: '/events', op: 'append', value: '提前抵达东塔' },
    ])
    expect(findSnapshotSubject(result?.snapshots ?? [], 'slice-erina-arrives', 'erina').attrs.location).toBe('subject://east-tower')
    expect(findSnapshotSubject(result?.snapshots ?? [], 'slice-erina-arrives', 'old-sword').attrs.owner).toBeUndefined()
  })

  it('解析审查工作台 value 草稿时区分 JSON-like 输入和普通文本', () => {
    expect(parseWorkbenchPreviewMutationValue('新王都')).toEqual({ ok: true, value: '新王都' })
    expect(parseWorkbenchPreviewMutationValue(' subject://capital ')).toEqual({ ok: true, value: ' subject://capital ' })
    expect(parseWorkbenchPreviewMutationValue('-10')).toEqual({ ok: true, value: -10 })
    expect(parseWorkbenchPreviewMutationValue('true')).toEqual({ ok: true, value: true })
    expect(parseWorkbenchPreviewMutationValue('null')).toEqual({ ok: true, value: null })
    expect(parseWorkbenchPreviewMutationValue('"80"')).toEqual({ ok: true, value: '80' })
    expect(parseWorkbenchPreviewMutationValue('{"level":"alert","locked":false}')).toEqual({
      ok: true,
      value: { level: 'alert', locked: false },
    })
    expect(parseWorkbenchPreviewMutationValue('{broken')).toEqual({
      ok: false,
      error: 'value 看起来像 JSON，但不是合法 JSON',
    })
    expect(formatWorkbenchPreviewValue({ level: 'normal', locked: true })).toBe('{"level":"normal","locked":true}')
  })

  it('共享 Slice List 过滤器同时覆盖 subject / kind / status / search', () => {
    const slices = cloneMockWorkbenchSlices()
    const openSummary = { confirmed: 0, done: 0, ignored: 0, open: 1, sliceId: 'slice-east-tower-opened', total: 1 }
    const doneSummary = { confirmed: 1, done: 1, ignored: 0, open: 0, sliceId: 'slice-east-tower-opened', total: 1 }
    const target = slices.find(slice => slice.id === 'slice-east-tower-opened')
    const clean = slices.find(slice => slice.id === 'slice-world-init')
    expect(target).toBeTruthy()
    expect(clean).toBeTruthy()

    expect(matchesWorkbenchPreviewSliceFilter({
      selectedSubjectIds: ['erina', 'old-sword'],
      slice: target!,
      sliceHealthFilter: 'open',
      sliceKindFilter: 'event',
      sliceReviewSummary: openSummary,
      sliceSearch: 'durability',
      subjectFilterMode: 'all',
    })).toBe(true)
    expect(matchesWorkbenchPreviewSliceFilter({
      selectedSubjectIds: ['erina', 'moran'],
      slice: target!,
      sliceHealthFilter: 'open',
      sliceKindFilter: 'event',
      sliceReviewSummary: openSummary,
      sliceSearch: 'durability',
      subjectFilterMode: 'all',
    })).toBe(false)
    expect(matchesWorkbenchPreviewSliceFilter({
      selectedSubjectIds: ['erina', 'moran'],
      slice: target!,
      sliceHealthFilter: 'done',
      sliceKindFilter: 'event',
      sliceReviewSummary: doneSummary,
      sliceSearch: '东塔',
      subjectFilterMode: 'any',
    })).toBe(true)
    expect(matchesWorkbenchPreviewSliceFilter({
      selectedSubjectIds: [],
      slice: clean!,
      sliceHealthFilter: 'clean',
      sliceKindFilter: 'init',
      sliceReviewSummary: undefined,
      sliceSearch: '王都',
      subjectFilterMode: 'any',
    })).toBe(true)
    expect(matchesWorkbenchPreviewSliceFilter({
      selectedSubjectIds: [],
      slice: clean!,
      sliceHealthFilter: 'draft',
      sliceKindFilter: 'all',
      sliceReviewSummary: undefined,
      sliceSearch: '',
      subjectFilterMode: 'any',
      metadataDraftCount: 0,
      valueDraftCount: 0,
    })).toBe(false)
    expect(matchesWorkbenchPreviewSliceFilter({
      selectedSubjectIds: [],
      slice: clean!,
      sliceHealthFilter: 'draft',
      sliceKindFilter: 'all',
      sliceReviewSummary: undefined,
      sliceSearch: '',
      subjectFilterMode: 'any',
      metadataDraftCount: 0,
      valueDraftCount: 1,
    })).toBe(true)
    expect(matchesWorkbenchPreviewSliceFilter({
      selectedSubjectIds: [],
      slice: clean!,
      sliceHealthFilter: 'draft',
      sliceKindFilter: 'all',
      sliceReviewSummary: undefined,
      sliceSearch: '',
      subjectFilterMode: 'any',
      metadataDraftCount: 1,
      valueDraftCount: 0,
    })).toBe(true)

    expect(buildWorkbenchPreviewFiltersAfterSavedEdit({
      editedSlice: target!,
      selectedSubjectIds: ['moran'],
      sliceHealthFilter: 'open',
      sliceKindFilter: 'init',
      sliceSearch: 'missing keyword',
      subjectFilterMode: 'all',
    })).toEqual({
      selectedSubjectIds: [],
      sliceHealthFilter: 'all',
      sliceKindFilter: 'all',
      sliceSearch: '',
      subjectFilterMode: 'any',
    })
    expect(buildWorkbenchPreviewFiltersAfterSavedEdit({
      editedSlice: target!,
      selectedSubjectIds: ['erina'],
      sliceHealthFilter: 'all',
      sliceKindFilter: 'event',
      sliceSearch: 'durability',
      subjectFilterMode: 'any',
    })).toEqual({
      selectedSubjectIds: ['erina'],
      sliceHealthFilter: 'all',
      sliceKindFilter: 'event',
      sliceSearch: 'durability',
      subjectFilterMode: 'any',
    })
  })

  it('识别主体系统维护切片，避免技术迁移记录默认占据主视图', () => {
    expect(isWorldWorkbenchSubjectSystemMaintenanceSlice({
      kind: 'init',
      title: '主体系统信息边界收口',
      summary: '移除 World Engine 当前状态中的主体系统源文件全文与 RAG 镜像',
    })).toBe(true)
    expect(isWorldWorkbenchSubjectSystemMaintenanceSlice({
      kind: 'init',
      title: '旧主体链接初始化',
      summary: '写入 sourcePath / legacyKind',
    })).toBe(true)
    expect(isWorldWorkbenchSubjectSystemMaintenanceSlice({
      kind: 'init',
      title: '主体经历记忆初始化',
      summary: '把 events.jsonl 作为角色 episodic memory',
    })).toBe(true)
    expect(isWorldWorkbenchSubjectSystemMaintenanceSlice({
      kind: 'event',
      title: '主体系统遭到破坏',
      summary: '这是世界内发生的事件，不是维护切片',
    })).toBe(false)
    expect(isWorldWorkbenchSubjectSystemMaintenanceSlice({
      kind: 'init',
      title: '创建 命定之诗世界',
      summary: '初始化世界 subject',
    })).toBe(false)
  })
})
